[build]
  publish = "dist"  # Make sure this matches your build output directory
  functions = "netlify/functions"
  command = "npm run build"  # Your build command

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  timeout = 30  # Increased timeout from default 10s to 30s
  
  # Explicitly include these directories when deploying functions
  included_files = ["node_modules/stripe/**", "node_modules/@supabase/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
