create table "public"."connected_customers" (
    "id" bigint generated by default as identity not null,
    "parent_id" uuid not null,
    "studio_id" uuid not null,
    "stripe_connected_customer_id" text,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."invoices" drop column "stripe_connect_account_id";

alter table "public"."invoices" drop column "uses_connect_account";

alter table "public"."invoices" alter column "status" set default 'draft'::text;

alter table "public"."payments" add column "stripe_invoice_id" text;

alter table "public"."studios" add column "currency" text default 'GBP'::text;

CREATE UNIQUE INDEX connected_customers_pkey ON public.connected_customers USING btree (id);

CREATE UNIQUE INDEX connected_customers_stripe_connected_customer_id_key ON public.connected_customers USING btree (stripe_connected_customer_id);

alter table "public"."connected_customers" add constraint "connected_customers_pkey" PRIMARY KEY using index "connected_customers_pkey";

alter table "public"."connected_customers" add constraint "connected_customers_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."connected_customers" validate constraint "connected_customers_parent_id_fkey";

alter table "public"."connected_customers" add constraint "connected_customers_stripe_connected_customer_id_key" UNIQUE using index "connected_customers_stripe_connected_customer_id_key";

alter table "public"."connected_customers" add constraint "connected_customers_studio_id_fkey" FOREIGN KEY (studio_id) REFERENCES studios(id) ON DELETE CASCADE not valid;

alter table "public"."connected_customers" validate constraint "connected_customers_studio_id_fkey";

grant delete on table "public"."connected_customers" to "anon";

grant insert on table "public"."connected_customers" to "anon";

grant references on table "public"."connected_customers" to "anon";

grant select on table "public"."connected_customers" to "anon";

grant trigger on table "public"."connected_customers" to "anon";

grant truncate on table "public"."connected_customers" to "anon";

grant update on table "public"."connected_customers" to "anon";

grant delete on table "public"."connected_customers" to "authenticated";

grant insert on table "public"."connected_customers" to "authenticated";

grant references on table "public"."connected_customers" to "authenticated";

grant select on table "public"."connected_customers" to "authenticated";

grant trigger on table "public"."connected_customers" to "authenticated";

grant truncate on table "public"."connected_customers" to "authenticated";

grant update on table "public"."connected_customers" to "authenticated";

grant delete on table "public"."connected_customers" to "service_role";

grant insert on table "public"."connected_customers" to "service_role";

grant references on table "public"."connected_customers" to "service_role";

grant select on table "public"."connected_customers" to "service_role";

grant trigger on table "public"."connected_customers" to "service_role";

grant truncate on table "public"."connected_customers" to "service_role";

grant update on table "public"."connected_customers" to "service_role";


